"""add media asset table

Revision ID: 391793a9abaf
Revises: 8425c0e2df9e
Create Date: 2021-05-25 10:04:05.938325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '391793a9abaf'
down_revision = '8425c0e2df9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('alt', sa.String(length=255), nullable=False),
                    sa.Column('file_name', sa.String(length=255), nullable=False),
                    sa.Column('path', sa.String(length=255), nullable=False),

                    sa.Column('country_code', sa.String(length=3), nullable=True),
                    sa.Column('city', sa.String(length=255), nullable=False, default=False),
                    sa.Column('move_to_location', sa.Integer(), sa.ForeignKey('stores_locations.id'), nullable=True),
                    sa.Column('is_close', sa.Boolean(), nullable=False, default=False),
                    sa.Column('create_at', sa.DateTime(), default=sa.func.current_timestamp()),
                    sa.Column('update_at', sa.DateTime(), onupdate=sa.ColumnDefault(sa.func.current_timestamp), default=sa.func.current_timestamp()),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stores_locations_store_id_fkey', 'stores_locations', type_='foreignkey')
    op.drop_constraint('stores_locations_move_to_location_fkey', 'stores_locations', type_='foreignkey')
    op.drop_table('stores_hours')
    # ### end Alembic commands ###toincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('move_to_location', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_close', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['move_to_location'], ['stores_locations.id'], name='stores_locations_move_to_location_fkey'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='stores_locations_store_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_locations_pkey')
    )
    op.create_table('stores_hours',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_time', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_time', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('is_open_24', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_close', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='stores_hours_store_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stores_hours_pkey')
    )
    # ### end Alembic commands ###
