"""add media asset table

Revision ID: 391793a9abaf
Revises: 8425c0e2df9e
Create Date: 2021-05-25 10:04:05.938325

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from src.utils.enums import MediaAssetsType

revision = '391793a9abaf'
down_revision = '8425c0e2df9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('alt', sa.String(length=255), nullable=False),
                    sa.Column('file_name', sa.String(length=255), index=True, nullable=False),
                    sa.Column('path', sa.String(length=255), nullable=False),
                    sa.Column('type', sa.Integer(), nullable=False, default=MediaAssetsType.Unknown),
                    sa.Column('width', sa.Integer(), nullable=True),
                    sa.Column('height', sa.Integer, nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_assets')
    # ### end Alembic commands ###
