"""store table locations

Revision ID: 8425c0e2df9e
Revises: 3d47f04f7046
Create Date: 2021-05-25 09:54:17.605585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d47f04f7046'
down_revision = '786cc7ba97f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores_locations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('store_id', sa.Integer(), sa.ForeignKey('stores.id')),
                    sa.Column('lat', sa.Integer(), nullable=True, index=True),
                    sa.Column('lng', sa.Integer(), nullable=True, index=True),
                    sa.Column('address', sa.String(length=255), nullable=False),
                    sa.Column('country_code', sa.String(length=3), nullable=True, index=False),
                    sa.Column('city', sa.String(length=255), nullable=False, default=False),
                    sa.Column('is_close', sa.Boolean(), nullable=False, default=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stores_locations_store_id_fkey', 'stores_locations', type_='foreignkey')

    op.drop_table('stores_hours')
    # ### end Alembic commands ###
