"""update media asset table to where it relevent

Revision ID: 45985f33020b
Revises: 391793a9abaf
Create Date: 2021-05-25 14:43:17.738685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45985f33020b'
down_revision = '391793a9abaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("users", "avatar_id", sa.ForeignKey('media_assets.id'))
    op.alter_column("stores", "logo_id", sa.ForeignKey('media_assets.id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", 'avatar_id', sa.Integer(), nullable=True)
    op.alter_column("stores", "logo_id", sa.Integer(), nullable=True)
    # ### end Alembic commands ###
