"""add development settings

Revision ID: 9b78715f7590
Revises: 9fa2c036d3ac
Create Date: 2021-06-20 22:18:33.196983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b78715f7590'
down_revision = '9fa2c036d3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    settings = sa.table('settings',
                        sa.Column('key', sa.Integer()),
                        sa.Column('environment', sa.String()),
                        sa.Column('description', sa.Text()),
                        sa.Column('is_json', sa.Boolean()),
                        sa.Column('value', sa.Text()))
    environments = ['development', 'testing']
    for environment in environments:
        op.bulk_insert(settings, [
            {
                'key': 'UPLOAD_MAX_SIZE',
                'environment': environment,
                'description': 'MAX upload size of the system',
                'is_json': False,
                'value': str(10 * 1024 * 1024)
            },
            {
                'key': 'UPLOAD_ALLOW_FILES_TYPES',
                'environment': environment,
                'description': 'Type of files allow in upload',
                'is_json': False,
                'value': 'jpg,jpeg,png,gif,doc,docx,xls,pdf,avi,mp4'
            },
        ])
    # ### end Alembic commands ###


def downgrade():
    pass
