"""add settings table

Revision ID: 9fa2c036d3ac
Revises: 29be447fbfe5
Create Date: 2021-06-20 17:47:49.329073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fa2c036d3ac'
down_revision = '29be447fbfe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
                    sa.Column('key', sa.String(length=255), index=True, nullable=False, unique=True),
                    sa.Column('environment', sa.String(length=50), index=True, nullable=False, unique=True),
                    sa.Column('description', sa.Text(), nullable=False, default=4),
                    sa.Column('is_json', sa.Boolean(), default=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), default=sa.func.current_timestamp()),
                    sa.Column('updated_at', sa.DateTime(), onupdate=sa.ColumnDefault(sa.func.current_timestamp), default=sa.func.current_timestamp()),
                    sa.PrimaryKeyConstraint(['key', 'environment']))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
