"""add roles table

Revision ID: cdd7027488fd
Revises: 9aa56c442f16
Create Date: 2021-05-19 21:04:36.166016

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cdd7027488fd'
down_revision = '02d930c305da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles = op.create_table('roles',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('name', sa.String(length=255), unique=True, index=True, nullable=False),
                            sa.Column('is_global', sa.Boolean(), default=False),
                            sa.Column('is_active', sa.Boolean(), default=True),
                            sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
