"""update user that passed tutrial

Revision ID: dbad07d7ae72
Revises: 18b3eb5a6735
Create Date: 2021-05-24 11:42:34.089588

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dbad07d7ae72'
down_revision = '18b3eb5a6735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pass_tutorial', sa.BOOLEAN(),
                                     nullable=False, default=False))
    op.add_column('users', sa.Column('store_code', sa.String(length=100),
                                     nullable=True, index=True))
    op.add_column('users', sa.Column('country', sa.String(length=3),
                                     nullable=True))
    op.add_column('users', sa.Column('currency', sa.String(length=3),
                                     nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_pass_tutorial')
    op.drop_column('users', 'store_code')
    op.drop_column('users', 'country')
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
