# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: Python application
on:
    push:
        branches: [ master ]
#   pull_request:
#     branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [ 3.9 ]

        steps:
            - name: echo-default-env-variables
              run: |
                  echo "Home: ${HOME}"
                  echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
                  echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
                  echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
                  echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
                  echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
                  echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Use Node v12
                uses: actions/setup-node@v1
                with:
                    node-version: 12
            -   name: Getting firebase config path
                shell: bash
                run: echo "::set-output name=path::$(echo ${GITHUB_WORKSPACE})/firebase-config.json"
                id: firebase_config_path

            -   name: Getting firebase admin config path
                shell: bash
                run: echo "::set-output name=path::$(echo ${GITHUB_WORKSPACE})/service-account-file.json"
                id: firebase_admin_config_path

            -   name: create firebase config file
                uses: schdck/create-env-json@v1
                with:
                    file-name: 'firebase-config.json'
                    apiKey: ${{ secrets.FIREBASE_API }}
                    authDomain: "10.0.0.31:9099"
                    databaseURL: "https://10.0.0.31:8080"
                    projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
                    storageBucket: "bmi-calc-project.appspot.com"
                    messagingSenderId: "521026165800"
                    appId: "1:521026165800:web:cc1afe28976024ea47291d"
                    measurementId: "G-N2DK47GTE1"
            -   name: create firebase admin config file
                uses: schdck/create-env-json@v1
                with:
                    file-name: 'service-account-file.json'
                    type": "service_account"
                    project_id": ${{ secrets.FIREBASE_PROJECT_ID }}
                    private_key_id": ${{ secrets.FIREBASE_ADMIN_CERT_ID }}
                    private_key": ${{ secrets.FIREBASE_ADMIN_CERT }}
                    client_email": "firebase-adminsdk-4kri0@bmi-calc-project.iam.gserviceaccount.com"
                    client_id": "110978043869639656704"
                    auth_uri": "https://accounts.google.com/o/oauth2/auth"
                    token_uri": "https://oauth2.googleapis.com/token"
                    auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"
                    client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-4kri0%40bmi-calc-project.iam.gserviceaccount.com"
            -   name: Make envfile
                uses: SpicyPizza/create-envfile@v1
                with:
                    SECRET_KEY: "123456abcdef"
                    DATABASE_URL: "postgresql://localhost:5432/postgres"
                    REDIS_HOST: "localhost"
                    REDIS_PORT: 6379
                    REDIS_DB: 0
                    REDIS_PASSWORD: ""
                    CACHE_KEY_PREFIX: "db_cache"
                    FIREBASE_APIKEY: ${{ secrets.FIREBASE_API }}
                    FIREBASE_SERVICE_CONFIG_FILE: ${{ steps.firebase_admin_config_path.path }}
                    FIREBASE_CONFIG_FILE: ${{ steps.firebase_config_path.path }}
                    file_name: .env.testing
            -   name: "Check file existence"
                uses: andstor/file-existence-action@v1
                with:
                    files: ".env.testing, firebase-config.json, service-account-file.json"
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install flake8 pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            -   name: Run integration tests against emulator
                env:
                    FLASK_ENV: 'testing'
                    FIREBASE_AUTH_EMULATOR_HOST: 'localhost:9099'
                    FIRESTORE_EMULATOR_HOST: 'localhost:8080'
                    FIRESTORE_STORAGE_EMULATOR_HOST: 'localhost:9199'
                run: |
                    npm install -g firebase-tools
                    firebase emulators:exec --only auth,firestore --project fake-project-id 'python -m unittest'